### ISSUE TITLE
error - jikjoo_moonstone

### ISSUE THREAD

**Issue by freshbell** [jikjoo/Bangul_webOS#27]
SyntaxError: Failed to execute 'matches' on 'Element': '.node_modules_@jikjoo_moonstone_Panels_Panel_body *' is not a valid selector.
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/utils.js:34
  31 | 
  32 | var matchSelector = (0, _curry["default"])(function (selector, elem) {
  33 |   if (typeof selector === 'string') {
> 34 |     return elementMatchesSelector.call(elem, selector);
  35 |   } else if (_typeof(selector) === 'object' && selector.length) {
  36 |     return selector.indexOf(elem) >= 0;
  37 |   } else if (_typeof(selector) === 'object' && selector.nodeType === 1) {
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/ramda/src/internal/_curryN.js:37
  34 |       }
  35 |       combinedIdx += 1;
  36 |     }
> 37 |     return left <= 0 ? fn.apply(this, combined)
  38 |                      : _arity(left, _curryN(length, combined, fn));
  39 |   };
  40 | };
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/ramda/src/internal/_arity.js:6
  3 | switch (n) {
  4 |   case 0: return function() { return fn.apply(this, arguments); };
  5 |   case 1: return function(a0) { return fn.apply(this, arguments); };
> 6 |   case 2: return function(a0, a1) { return fn.apply(this, arguments); };
    | ^  7 |   case 3: return function(a0, a1, a2) { return fn.apply(this, arguments); };
  8 |   case 4: return function(a0, a1, a2, a3) { return fn.apply(this, arguments); };
  9 |   case 5: return function(a0, a1, a2, a3, a4) { return fn.apply(this, arguments); };
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/container.js:747
  744 | 
  745 | if (typeof selector === 'string') {
  746 |   return spottables.filter(function (elem) {
> 747 |     return (0, _utils.matchSelector)(selector, elem) && isNavigable(elem, containerId, true);
      | ^  748 |   })[0];
  749 | } // FIXME: There is some prior implicit support for `defaultElement` to be an element rather
  750 | // than a selector. This continues that support but should eventually be removed.
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/container.js:746
  743 | }
  744 | 
  745 | if (typeof selector === 'string') {
> 746 |   return spottables.filter(function (elem) {
      | ^  747 |     return (0, _utils.matchSelector)(selector, elem) && isNavigable(elem, containerId, true);
  748 |   })[0];
  749 | } // FIXME: There is some prior implicit support for `defaultElement` to be an element rather
View compiled
getContainerDefaultElement
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/container.js:740
  737 | 
  738 | defaultElementSelector = (0, _util.coerceArray)(defaultElementSelector);
  739 | var spottables = getDeepSpottableDescendants(containerId);
> 740 | return defaultElementSelector.reduce(function (result, selector) {
      | ^  741 |   if (result) {
  742 |     return result;
  743 |   }
View compiled
getContainerNavigableElements
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/container.js:844
  841 | 
  842 | 
  843 | if (!next) {
> 844 |   next = getContainerDefaultElement(containerId);
      | ^  845 | }
  846 | 
  847 | if (!next) {
View compiled
getContainerFocusTarget
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/container.js:888
  885 | function getContainerFocusTarget(containerId) {
  886 |   // deferring restoration until it's requested to allow containers to prepare first
  887 |   restoreLastFocusedElement(containerId);
> 888 |   var next = getContainerNavigableElements(containerId); // If multiple candidates returned, we need to find the first viable target since some may
  889 |   // be empty containers which should be skipped.
  890 | 
  891 |   return next.reduce(function (result, element) {
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/target.js:81
  78 | 
  79 | function getTargetByContainer(containerId) {
  80 |   return getContainersToSearch(containerId).reduce(function (next, id) {
> 81 |     return next || (0, _container.getContainerFocusTarget)(id);
  82 |   }, null);
  83 | }
  84 | 
View compiled
getTargetByContainer
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/target.js:80
  77 | }
  78 | 
  79 | function getTargetByContainer(containerId) {
> 80 |   return getContainersToSearch(containerId).reduce(function (next, id) {
  81 |     return next || (0, _container.getContainerFocusTarget)(id);
  82 |   }, null);
  83 | }
View compiled
focus
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/spotlight/src/spotlight.js:693
  690 |   target = (0, _target.getTargetByContainer)();
  691 | } else if (typeof elem === 'string') {
  692 |   if ((0, _container.getContainerConfig)(elem)) {
> 693 |     target = (0, _target.getTargetByContainer)(elem);
      | ^  694 |     wasContainerId = true;
  695 |   } else if (/^[\w\d-]+$/.test(elem)) {
  696 |     // support component IDs consisting of alphanumeric, dash, or underscore
View compiled
spotOnRender
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@jikjoo/moonstone/Panels/Panel.js:166
  163 | 
  164 |       _spotlight["default"].set(spotlightId, config);
  165 | 
> 166 |       _spotlight["default"].focus(spotlightId);
      | ^  167 |     }
  168 |   }
  169 | },
View compiled
handlers.<computed>
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/@enact/core/kind/kind.js:199
  196 |     var _this2 = this;
  197 | 
  198 |     this.handlers[prop] = function (ev) {
> 199 |       return handler(ev, _this2.props, _this2.context);
      | ^  200 |     };
  201 |   }
  202 | }, {
View compiled
commitAttachRef
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:20023
  20020 | } // Moved outside to ensure DCE works with this flag
  20021 | 
  20022 | if (typeof ref === 'function') {
> 20023 |   ref(instanceToUse);
        | ^  20024 | } else {
  20025 |   {
  20026 |     if (!ref.hasOwnProperty('current')) {
View compiled
commitLayoutEffects
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:22808
  22805 | 
  22806 | if (effectTag & Ref) {
  22807 |   recordEffect();
> 22808 |   commitAttachRef(nextEffect);
        | ^  22809 | }
  22810 | 
  22811 | resetCurrentFiber();
View compiled
HTMLUnknownElement.callCallback
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:188
  185 |     window.event = windowEvent;
  186 |   }
  187 | 
> 188 |   func.apply(context, funcArgs);
      | ^  189 |   didError = false;
  190 | } // Create a global error event handler. We use this to capture the value
  191 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:237
  234 | // errors, it will trigger our global error handler.
  235 | 
  236 | evt.initEvent(evtType, false, false);
> 237 | fakeNode.dispatchEvent(evt);
      | ^  238 | 
  239 | if (windowEventDescriptor) {
  240 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:292
  289 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  290 |   hasError = false;
  291 |   caughtError = null;
> 292 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  293 | }
  294 | /**
  295 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
commitRootImpl
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:22541
  22538 | 
  22539 | do {
  22540 |   {
> 22541 |     invokeGuardedCallback(null, commitLayoutEffects, null, root, expirationTime);
        | ^  22542 | 
  22543 |     if (hasCaughtError()) {
  22544 |       if (!(nextEffect !== null)) {
View compiled
unstable_runWithPriority
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/scheduler/cjs/scheduler.development.js:653
  650 | currentPriorityLevel = priorityLevel;
  651 | 
  652 | try {
> 653 |   return eventHandler();
      | ^  654 | } finally {
  655 |   currentPriorityLevel = previousPriorityLevel;
  656 | }
View compiled
runWithPriority$1
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:11039
  11036 | 
  11037 | function runWithPriority$1(reactPriorityLevel, fn) {
  11038 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11039 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11040 | }
  11041 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11042 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
View compiled
commitRoot
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:22381
  22378 | 
  22379 | function commitRoot(root) {
  22380 |   var renderPriorityLevel = getCurrentPriorityLevel();
> 22381 |   runWithPriority$1(ImmediatePriority, commitRootImpl.bind(null, root, renderPriorityLevel));
  22382 |   return null;
  22383 | }
  22384 | 
View compiled
finishSyncRender
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:21807
  21804 | function finishSyncRender(root) {
  21805 |   // Set this to null to indicate there's no in-progress render.
  21806 |   workInProgressRoot = null;
> 21807 |   commitRoot(root);
  21808 | }
  21809 | function flushDiscreteUpdates() {
  21810 |   // TODO: Should be able to flush inside batchedUpdates, but not inside `act`.
View compiled
performSyncWorkOnRoot
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:21793
  21790 |   stopFinishedWorkLoopTimer();
  21791 |   root.finishedWork = root.current.alternate;
  21792 |   root.finishedExpirationTime = expirationTime;
> 21793 |   finishSyncRender(root);
        | ^  21794 | } // Before exiting, make sure there's a callback scheduled for the next
  21795 | // pending level.
  21796 | 
View compiled
scheduleUpdateOnFiber
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:21188
  21185 |   // root inside of batchedUpdates should be synchronous, but layout updates
  21186 |   // should be deferred until the end of the batch.
  21187 | 
> 21188 |   performSyncWorkOnRoot(root);
        | ^  21189 | } else {
  21190 |   ensureRootIsScheduled(root);
  21191 |   schedulePendingInteractions(root, expirationTime);
View compiled
updateContainer
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:24373
  24370 |   }
  24371 | 
  24372 |   enqueueUpdate(current$1, update);
> 24373 |   scheduleWork(current$1, expirationTime);
  24374 |   return expirationTime;
  24375 | }
  24376 | function getPublicRootInstance(container) {
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:24758
  24755 | 
  24756 | 
  24757 |   unbatchedUpdates(function () {
> 24758 |     updateContainer(children, fiberRoot, parentComponent, callback);
        | ^  24759 |   });
  24760 | } else {
  24761 |   fiberRoot = root._internalRoot;
View compiled
unbatchedUpdates
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:21903
  21900 | executionContext |= LegacyUnbatchedContext;
  21901 | 
  21902 | try {
> 21903 |   return fn(a);
        | ^  21904 | } finally {
  21905 |   executionContext = prevExecutionContext;
  21906 | 
View compiled
legacyRenderSubtreeIntoContainer
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:24757
  24754 |   } // Initial mount should not be batched.
  24755 | 
  24756 | 
> 24757 |   unbatchedUpdates(function () {
        | ^  24758 |     updateContainer(children, fiberRoot, parentComponent, callback);
  24759 |   });
  24760 | } else {
View compiled
render
C:/Users/freshbell/webOS/Bangul_webOS/node_modules/react-dom/cjs/react-dom.development.js:24840
  24837 |     }
  24838 |   }
  24839 | 
> 24840 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  24841 | }
  24842 | function unstable_renderSubtreeIntoContainer(parentComponent, element, containerNode, callback) {
  24843 |   if (!isValidContainer(containerNode)) {
View compiled
Module../src/index.js
C:/Users/freshbell/webOS/Bangul_webOS/src/index.js:15
  12 | 
  13 | // In a browser environment, render instead of exporting
  14 | if (typeof window !== 'undefined') {
> 15 | 	render(
  16 | 		appElement,
  17 | 		document.getElementById('root')
  18 | 	);
View compiled
__webpack_require__
C:/Users/freshbell/webOS/Bangul_webOS/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
C:/Users/freshbell/webOS/Bangul_webOS/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
1
http://localhost:8080/main.js:135951:18
__webpack_require__
C:/Users/freshbell/webOS/Bangul_webOS/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
(anonymous function)
C:/Users/freshbell/webOS/Bangul_webOS/webpack/bootstrap:858
  855 | 
  856 | 
  857 | // Load entry module and return exports
> 858 | return hotCreateRequire(1)(__webpack_require__.s = 1);
      | ^  859 | 
View compiled
(anonymous function)
http://localhost:8080/main.js:862:10

**Comment by jikjoo** [comment]
```js
import { Panel, Header } from '@jikjoo/moonstone/Panels';
```
=> 
```js
import  Panel ,{, Header } from '@jikjoo/moonstone/Panels';
```
~로 다 바꾸기~

**Comment by jikjoo** [comment]
`npm install -g @enact/cli@2.8.1` 로 enact cli 버전 바꾸기
